creation_rules:
  - path_regex: ^machines/gaia/secrets/.*$
    key_groups:
      - age:
          - age1frvu2rns8l8ekq64hhej4twvqgu54lcepu2vgw89ggpp4t8tfpkqnmn4eq
  - path_regex: ^secrets/wikimem-gaia\.enc$
    key_groups:
      - age:
          - age1frvu2rns8l8ekq64hhej4twvqgu54lcepu2vgw89ggpp4t8tfpkqnmn4eq
          - age1g94ghgrt9wslamjwv6kqd2wnu6d7chtd2d50fva86j80psx4hgpqydmhcr
  - path_regex: ^secrets/wikimem-blackmoon\.enc$
    key_groups:
      - age:
          - age1frvu2rns8l8ekq64hhej4twvqgu54lcepu2vgw89ggpp4t8tfpkqnmn4eq
          - age1rrl7ln5q304rka3y9rwqvxc7yjxcwzgdsv4gzfvqcuysk5xkn96q89muec
  - path_regex: ^secrets/wikimem-comet\.enc$
    key_groups:
      - age:
          - age1frvu2rns8l8ekq64hhej4twvqgu54lcepu2vgw89ggpp4t8tfpkqnmn4eq
          - age1n692uq0djn9n6ppth7ey5jplxqgk0u3num9a95xskezguaj2uqjslsyj03
  - path_regex: ^secrets/wikimem-oasis\.enc$
    key_groups:
      - age:
          - age1frvu2rns8l8ekq64hhej4twvqgu54lcepu2vgw89ggpp4t8tfpkqnmn4eq
          - age1mpn7ea5yh0wcf9datjn6rvnfywqhd9drzpfthns4pql6wfnt4desfzvrmd
