{
  config,
  lib,
  variables,
  ...
}: let
  cfg = config.wayland.windowManager.hyprland;
  luaVars = variables.hyprlandLua or {};
  enableActiveLua = luaVars.enable or false;

  inherit (lib) concatMapStringsSep concatStringsSep filterAttrs hasPrefix mapAttrsToList optionalAttrs;

  luaString = value: builtins.toJSON (toString value);
  luaScalar = value:
    if builtins.isBool value
    then
      if value
      then "true"
      else "false"
    else if builtins.isInt value || builtins.isFloat value
    then toString value
    else if value == null
    then "nil"
    else if builtins.isString value && value == "true"
    then "true"
    else if builtins.isString value && value == "false"
    then "false"
    else if builtins.isString value && builtins.match "-?[0-9]+(\\.[0-9]+)?" value != null
    then value
    else luaString value;

  luaKey = key:
    if builtins.match "[A-Za-z_][A-Za-z0-9_]*" key != null
    then key
    else "[${luaString key}]";

  luaValue = value:
    if builtins.isAttrs value
    then luaTable value
    else if builtins.isList value
    then "{${concatMapStringsSep ", " luaValue value}}"
    else luaScalar value;

  luaTable = attrs: let
    entries = mapAttrsToList (name: value: "${luaKey name} = ${luaValue value}") attrs;
  in "{${concatStringsSep ", " entries}}";

  luaLines = lines: concatStringsSep "\n" lines;
  indent = text:
    concatStringsSep "\n" (map (line: "  ${line}") (lib.splitString "\n" text));

  specialTopLevel = [
    "$"
    "bind"
    "binde"
    "bindm"
    "bindr"
    "env"
    "exec-once"
    "exec-shutdown"
    "gesture"
    "layerrule"
    "monitors"
    "nvidia"
    "windowrule"
    "windowrulev2"
  ];

  isSpecialName = name:
    name
    == "monitors"
    || builtins.elem name specialTopLevel
    || hasPrefix "$" name;

  scalarConfigSettings = let
    base = filterAttrs (name: _value: !(isSpecialName name) && name != "cliphist") cfg.settings;
    animations = (base.animations or {}) // {};
  in
    (removeAttrs base ["animations"])
    // optionalAttrs (animations != {}) {
      animations = removeAttrs animations ["animation" "bezier"];
    };

  configSettings =
    lib.filterAttrsRecursive (_name: value: value != {} && value != []) scalarConfigSettings;

  legacyVars =
    filterAttrs (name: _value: hasPrefix "$" name) cfg.settings;

  mkVarLines =
    mapAttrsToList (name: value: "var(${luaString name}, ${luaString value})") legacyVars;

  mkExecLines = event: commands:
    lib.optionals (commands != []) [
      "hl.on(${luaString event}, function()"
      (indent (luaLines (map (cmd: "hl.exec_cmd(expand(${luaString cmd}))") commands)))
      "end)"
    ];

  mkEnvLines = envs:
    map (entry: let
      parts =
        if builtins.match ".*,.*" entry != null
        then lib.splitString "," entry
        else lib.splitString "=" entry;
      name = lib.head parts;
      value =
        if builtins.match ".*,.*" entry != null
        then concatStringsSep "," (lib.tail parts)
        else concatStringsSep "=" (lib.tail parts);
    in "hl.env(${luaString name}, expand(${luaString value}))")
    envs;

  mkMonitorLines = monitors:
    map (entry: "legacy_monitor(${luaString entry})") monitors;

  mkWorkspaceRuleLines = rules:
    map (entry: "legacy_workspace_rule(${luaString entry})") rules;

  monitors = cfg.settings.monitors.monitor or [];
  workspaceRules = cfg.settings.monitors.workspace or [];

  mkBindLines = kind: binds: let
    flags =
      if kind == "bindm"
      then "{ mouse = true }"
      else if kind == "bindr"
      then "{ release = true }"
      else if kind == "binde"
      then "{ repeating = true }"
      else "nil";
  in
    map (bind: "legacy_bind(${luaString bind}, ${flags})") binds;

  mkWindowRuleLines = rules:
    map (rule: "legacy_window_rule(${luaString rule})") rules;

  mkLayerRuleLines = rules:
    map (rule: "legacy_layer_rule(${luaString rule})") rules;

  mkGestureLines = gestures:
    map (gesture: "legacy_gesture(${luaString gesture})") gestures;

  mkAnimationLines = animations: let
    curves = lib.optionals (animations ? bezier) [animations.bezier];
    animationEntries = animations.animation or [];
  in
    map (curve: "legacy_bezier(${luaString curve})") curves
    ++ map (animation: "legacy_animation(${luaString animation})") animationEntries;

  extraConfigLines =
    builtins.filter (line: line != "") (map (line: lib.trim line) (lib.splitString "\n" (cfg.extraConfig or "")));

  mkExtraConfigLines =
    map (line: "legacy_extra_config(${luaString line})") extraConfigLines;

  cliphistExec = cfg.settings.cliphist."exec-once" or [];
  cliphistBind = lib.optional ((cfg.settings.cliphist or {}) ? bind) cfg.settings.cliphist.bind;

  generatedLua = luaLines ([
      "-- Generated by home/apps/hypr/hyprland-lua.nix."
      "-- Preview path: ~/.config/hypr/hyprland.generated.lua"
      "-- Set variables.hyprlandLua.enable = true to install this as ~/.config/hypr/hyprland.lua."
      ""
      "local vars = {}"
      ""
      "local function var(name, value)"
      "  vars[name] = value"
      "end"
      ""
      "local function expand(value)"
      "  return (value:gsub(\"%$[%w_]+\", function(name)"
      "    return vars[name] or name"
      "  end))"
      "end"
      ""
    ]
    ++ mkVarLines
    ++ [
      ""
      "local function split_csv(value)"
      "  local result = {}"
      "  for part in string.gmatch(value, \"([^,]+)\") do"
      "    table.insert(result, (part:gsub(\"^%s+\", \"\"):gsub(\"%s+$\", \"\")))"
      "  end"
      "  return result"
      "end"
      ""
      "local function key_expr(mods, key)"
      "  local expanded_mods = expand(mods)"
      "  key = key:gsub(\"^%s+\", \"\"):gsub(\"%s+$\", \"\")"
      "  key = ({ [\"return\"] = \"Return\" })[key] or key"
      "  if expanded_mods == \"\" then"
      "    return key"
      "  end"
      "  return (expanded_mods:gsub(\"%s+\", \" + \")) .. \" + \" .. key"
      "end"
      ""
      "local function dispatcher(name, arg, mouse)"
      "  name = name:gsub(\"^%s+\", \"\"):gsub(\"%s+$\", \"\")"
      "  arg = expand((arg or \"\"):gsub(\"^%s+\", \"\"):gsub(\"%s+$\", \"\"))"
      "  if name == \"exec\" then return hl.dsp.exec_cmd(arg) end"
      "  if name == \"killactive\" then return hl.dsp.window.close() end"
      "  if name == \"exit\" then return hl.dsp.exit() end"
      "  if name == \"togglefloating\" then return hl.dsp.window.float({ action = \"toggle\" }) end"
      "  if name == \"fullscreen\" then return hl.dsp.window.fullscreen({ action = \"toggle\" }) end"
      "  if name == \"pseudo\" then return hl.dsp.window.pseudo({ action = \"toggle\" }) end"
      "  if name == \"workspace\" then return hl.dsp.focus({ workspace = arg }) end"
      "  if name == \"movetoworkspace\" then return hl.dsp.window.move({ workspace = arg }) end"
      "  if name == \"togglespecialworkspace\" then return hl.dsp.workspace.toggle_special(arg) end"
      "  if name == \"layoutmsg\" then return hl.dsp.layout(arg) end"
      "  if name == \"movefocus\" then return hl.dsp.focus({ direction = arg }) end"
      "  if name == \"swapwindow\" then return hl.dsp.window.swap({ direction = arg }) end"
      "  if name == \"movewindow\" and mouse then return hl.dsp.window.drag() end"
      "  if name == \"resizewindow\" and mouse then return hl.dsp.window.resize() end"
      "  if name == \"movewindow\" then return hl.dsp.window.move({ direction = arg }) end"
      "  return hl.dsp.exec_cmd(\"hyprctl dispatch \" .. name .. (arg ~= \"\" and \" \" .. arg or \"\"))"
      "end"
      ""
      "local function legacy_bind(line, flags)"
      "  local parts = split_csv(line)"
      "  local mods = parts[1] or \"\""
      "  local key = parts[2] or \"\""
      "  local disp = parts[3] or \"\""
      "  local arg = table.concat(parts, \",\", 4)"
      "  hl.bind(key_expr(mods, key), dispatcher(disp, arg, flags and flags.mouse), flags or nil)"
      "end"
      ""
      "local function legacy_monitor(line)"
      "  local p = split_csv(line)"
      "  local spec = { output = p[1] or \"\", mode = p[2] or \"preferred\", position = p[3] or \"auto\", scale = p[4] or \"auto\" }"
      "  local i = 5"
      "  while p[i] do"
      "    local key, value = p[i], p[i + 1]"
      "    if key == \"transform\" then spec.transform = tonumber(value) or value end"
      "    if key == \"bitdepth\" then spec.bitdepth = tonumber(value) or value end"
      "    if key == \"vrr\" then spec.vrr = tonumber(value) or value end"
      "    i = i + 2"
      "  end"
      "  hl.monitor(spec)"
      "end"
      ""
      "local function legacy_workspace_rule(line)"
      "  local p = split_csv(line)"
      "  local spec = { workspace = p[1] or \"\" }"
      "  for i = 2, #p do"
      "    local key, value = p[i]:match(\"^([^:]+):(.+)$\")"
      "    if key == \"monitor\" then spec.monitor = value end"
      "    if key == \"default\" then spec.default = value == \"true\" end"
      "  end"
      "  hl.workspace_rule(spec)"
      "end"
      ""
      "local function parse_boolish(value)"
      "  if value == nil or value == \"\" then return true end"
      "  if value == \"1\" or value == \"true\" then return true end"
      "  if value == \"0\" or value == \"false\" then return false end"
      "  return value"
      "end"
      ""
      "local function legacy_window_rule(line)"
      "  local spec = { match = {} }"
      "  for _, token in ipairs(split_csv(line)) do"
      "    local prop, match_value = token:match(\"^match:([^%s]+)%s+(.+)$\")"
      "    if prop then"
      "      spec.match[prop] = match_value"
      "    else"
      "      local effect, value = token:match(\"^([^%s]+)%s*(.*)$\")"
      "      if effect == \"workspace\" then spec.workspace = value"
      "      elseif effect == \"monitor\" then spec.monitor = value:gsub(\"%s+tile$\", \"\"); if value:match(\"%s+tile$\") then spec.tile = true end"
      "      elseif effect == \"center\" then spec.center = parse_boolish(value)"
      "      elseif effect == \"idle_inhibit\" then spec.idle_inhibit = value"
      "      elseif effect == \"render_unfocused\" then spec.render_unfocused = parse_boolish(value)"
      "      elseif effect == \"tile\" then spec.tile = parse_boolish(value)"
      "      elseif effect == \"float\" then spec.float = parse_boolish(value)"
      "      else spec[effect] = parse_boolish(value) end"
      "    end"
      "  end"
      "  hl.window_rule(spec)"
      "end"
      ""
      "local function legacy_layer_rule(line)"
      "  local spec = { match = {} }"
      "  for _, token in ipairs(split_csv(line)) do"
      "    local prop, match_value = token:match(\"^match:([^%s]+)%s+(.+)$\")"
      "    if prop then"
      "      spec.match[prop] = match_value"
      "    else"
      "      local effect, value = token:match(\"^([^%s]+)%s*(.*)$\")"
      "      if effect == \"blur\" then spec.blur = value == \"on\" or value == \"1\" or value == \"true\""
      "      elseif effect == \"dim_around\" then spec.dim_around = value == \"on\" or value == \"1\" or value == \"true\""
      "      elseif effect == \"ignore_alpha\" then spec.ignore_alpha = tonumber(value) or value"
      "      elseif effect == \"order\" then spec.order = tonumber(value) or value"
      "      elseif effect == \"animation\" then spec.animation = value"
      "      else spec[effect] = parse_boolish(value) end"
      "    end"
      "  end"
      "  hl.layer_rule(spec)"
      "end"
      ""
      "local function legacy_bezier(line)"
      "  local p = split_csv(line)"
      "  hl.curve(p[1], { type = \"bezier\", points = { { tonumber(p[2]), tonumber(p[3]) }, { tonumber(p[4]), tonumber(p[5]) } } })"
      "end"
      ""
      "local function legacy_animation(line)"
      "  local p = split_csv(line)"
      "  hl.animation({ leaf = p[1], enabled = p[2] == \"1\" or p[2] == \"true\", speed = tonumber(p[3]), curve = p[4], style = table.concat(p, \" \", 5) })"
      "end"
      ""
      "local function legacy_gesture(line)"
      "  local p = split_csv(line)"
      "  hl.gesture({ fingers = tonumber(p[1]), direction = p[2], action = table.concat(p, \",\", 3) })"
      "end"
      ""
      "local function legacy_extra_config(line)"
      "  local plugin = line:match(\"^plugin%s*=%s*(.+)$\")"
      "  if plugin then"
      "    hl.plugin.load(plugin)"
      "  end"
      "end"
      ""
      "hl.config(${luaTable configSettings})"
      ""
    ]
    ++ mkAnimationLines (cfg.settings.animations or {})
    ++ mkExtraConfigLines
    ++ mkExecLines "hyprland.start" (cfg.settings."exec-once" or [])
    ++ mkExecLines "hyprland.start" cliphistExec
    ++ mkExecLines "hyprland.shutdown" (cfg.settings."exec-shutdown" or [])
    ++ mkEnvLines (cfg.settings.env or [])
    ++ mkEnvLines (cfg.settings.nvidia.env or [])
    ++ mkMonitorLines monitors
    ++ mkWorkspaceRuleLines workspaceRules
    ++ mkBindLines "bind" (cfg.settings.bind or [])
    ++ mkBindLines "bind" cliphistBind
    ++ mkBindLines "binde" (cfg.settings.binde or [])
    ++ mkBindLines "bindm" (cfg.settings.bindm or [])
    ++ mkBindLines "bindr" (cfg.settings.bindr or [])
    ++ mkWindowRuleLines (cfg.settings.windowrule or [])
    ++ mkWindowRuleLines (cfg.settings.windowrulev2 or [])
    ++ mkLayerRuleLines (cfg.settings.layerrule or [])
    ++ mkGestureLines (cfg.settings.gesture or []));
in {
  config = lib.mkIf cfg.enable {
    home.file =
      {
        ".config/hypr/hyprland.generated.lua".text = generatedLua;
      }
      // optionalAttrs enableActiveLua {
        ".config/hypr/hyprland.lua".text = generatedLua;
      };
  };
}
